module.exports.availableLanguages = [
	['ar', 'Arabic'],
	['bn', 'Bengali (Bangla)'],
	['bh', 'Bihari'],
	['zh', 'Chinese'],
	['zh-Hans', 'Chinese (Simplified)'],
	['zh-Hant', 'Chinese (Traditional)'],
	['cs', 'Czech'],
	['nl', 'Dutch'],
	['en-US', 'English (US)'],
	['en-UK', 'English (UK)'],
	['fr', 'French'],
	['el', 'Greek'],
	['gu', 'Gujarati'],
	['hi', 'Hindi'],
	['id', 'Indonesian'],
	['it', 'Italian'],
	['ja', 'Japanese'],
	['la', 'Latin'],
	['ne', 'Nepali'],
	['pl', 'Polish'],
	['pt', 'Portuguese'],
	['pa', 'Punjabi (Eastern)'],
	['ru', 'Russian'],
	['sa', 'Sanskrit'],
	['es', 'Spanish'],
	['sv', 'Swedish'],
	['ta', 'Tamil'],
	['te', 'Telugu'],
	['th', 'Thai'],
	['bo', 'Tibetan'],
	['tr', 'Turkish'],
	['uk', 'Ukrainian'],
	['ur', 'Urdu'],
	['vi', 'Vietnamese'],
	['zu', 'Zulu'],
];
